linters:
  eslint:
    config: './.eslintrc.json'

  stylelint:
    config: './.stylelintrc.json'
    fixer: true
    
files:
  ignore:
    - 'node_modules/*'
    - 'src/**.test.js'
    - 'src/setupTests.js'